spring:
  datasource:
    url: jdbc:postgresql://smart-home-monolith-postgresql.default:5432/smart_home
    username: postgres
    password: postgres
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:init.sql

server:
  port: 8080
